# pyright: strict
"""Typed public interface for the binary-schema DSL.

Typical usage::

    class Header(Schema):
        kind = Int8(fixed(1))
        body_length = Int16()

    class Packet(Schema):
        header = Header()

        @Block[header.body_length]
        class body(Schema):
            payload = Blob[header.body_length]()

``Field`` and nested Schema members can be used in length expressions.  An
``Expr`` may contain at most one field reference.  ``PacketUnion`` marks the
single ``Union`` in an entry schema; Peach export then emits reusable DataModels
and ``Block ref`` overrides.
"""

from collections.abc import Callable, Mapping
from typing import Any, Generic, Literal, Self, TypeVar, overload

T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)
S = TypeVar("S", bound="Schema")
Endian = Literal["big", "little"]
StringEncoding = Literal["ascii", "utf7", "utf8", "utf16", "utf16be", "utf32", "utf32be"]
ScalarValue = int | float | str | bytes
ExtendedValue = TypeVar("ExtendedValue", bound=ScalarValue)


class _ConstraintNode:
    """Internal base for symbolic constraint operands."""
    pass


class Fixed(Generic[T_co]):
    """A wire value fixed by the schema, created with :func:`fixed`."""
    @property
    def value(self) -> T_co: ...


def fixed(value: T) -> Fixed[T]: ...


class ConstraintValue(_ConstraintNode, Generic[T]):
    """Type-only parameter of a ``constraint=lambda value: ...`` expression."""
    def __len__(self: ConstraintValue[str] | ConstraintValue[bytes]) -> int: ...
    @overload
    def __getitem__(self: ConstraintValue[str], index: int) -> str: ...
    @overload
    def __getitem__(self: ConstraintValue[bytes], index: int) -> int: ...
    def __add__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __radd__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __sub__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __rsub__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __mul__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __rmul__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __floordiv__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __rfloordiv__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __mod__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __rmod__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __and__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __rand__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __or__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __ror__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __xor__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __rxor__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __lshift__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __rlshift__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __rshift__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __rrshift__(self: ConstraintValue[int], other: int) -> Expr: ...
    def __eq__(self, other: T) -> Expr: ...  # type: ignore[override]
    def __ne__(self, other: T) -> Expr: ...  # type: ignore[override]
    def __lt__(self: ConstraintValue[int] | ConstraintValue[float], other: int | float) -> Expr: ...
    def __le__(self: ConstraintValue[int] | ConstraintValue[float], other: int | float) -> Expr: ...
    def __gt__(self: ConstraintValue[int] | ConstraintValue[float], other: int | float) -> Expr: ...
    def __ge__(self: ConstraintValue[int] | ConstraintValue[float], other: int | float) -> Expr: ...


class Expr:
    """Symbolic arithmetic, bitwise, or comparison expression for one Field."""
    operation: str
    left: ExprOperand
    right: ExprOperand
    @property
    def op(self) -> str: ...
    def __add__(self, other: ExprOperand) -> Expr: ...
    def __radd__(self, other: ExprOperand) -> Expr: ...
    def __sub__(self, other: ExprOperand) -> Expr: ...
    def __rsub__(self, other: ExprOperand) -> Expr: ...
    def __mul__(self, other: ExprOperand) -> Expr: ...
    def __rmul__(self, other: ExprOperand) -> Expr: ...
    def __floordiv__(self, other: ExprOperand) -> Expr: ...
    def __rfloordiv__(self, other: ExprOperand) -> Expr: ...
    def __mod__(self, other: ExprOperand) -> Expr: ...
    def __rmod__(self, other: ExprOperand) -> Expr: ...
    def __and__(self, other: ExprOperand) -> Expr: ...
    def __rand__(self, other: ExprOperand) -> Expr: ...
    def __or__(self, other: ExprOperand) -> Expr: ...
    def __ror__(self, other: ExprOperand) -> Expr: ...
    def __xor__(self, other: ExprOperand) -> Expr: ...
    def __rxor__(self, other: ExprOperand) -> Expr: ...
    def __lshift__(self, other: ExprOperand) -> Expr: ...
    def __rlshift__(self, other: ExprOperand) -> Expr: ...
    def __rshift__(self, other: ExprOperand) -> Expr: ...
    def __rrshift__(self, other: ExprOperand) -> Expr: ...
    def __eq__(self, other: ExprOperand) -> Expr: ...  # type: ignore[override]
    def __ne__(self, other: ExprOperand) -> Expr: ...  # type: ignore[override]
    def __lt__(self, other: ExprOperand) -> Expr: ...
    def __le__(self, other: ExprOperand) -> Expr: ...
    def __gt__(self, other: ExprOperand) -> Expr: ...
    def __ge__(self, other: ExprOperand) -> Expr: ...


class Field(Generic[T_co]):
    """One scalar field.  Class access is a declaration; instance access is a reference."""
    kind: str
    @overload
    def __get__(self, instance: None, owner: type[Schema]) -> Field[T_co]: ...
    @overload
    def __get__(self, instance: _SchemaInstance, owner: type[Schema]) -> MemberRef[T_co]: ...
    def __add__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __radd__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __sub__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __rsub__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __mul__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __rmul__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __floordiv__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __rfloordiv__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __mod__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __rmod__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __eq__(self: Field[int] | Field[str], other: ExprOperand) -> Expr: ...  # type: ignore[override]
    def __ne__(self: Field[int] | Field[str], other: ExprOperand) -> Expr: ...  # type: ignore[override]
    def __lt__(self: Field[int] | Field[str], other: ExprOperand) -> Expr: ...
    def __le__(self: Field[int] | Field[str], other: ExprOperand) -> Expr: ...
    def __gt__(self: Field[int] | Field[str], other: ExprOperand) -> Expr: ...
    def __ge__(self: Field[int] | Field[str], other: ExprOperand) -> Expr: ...
    def __and__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __rand__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __or__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __ror__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __xor__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __rxor__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __lshift__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __rlshift__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __rshift__(self: Field[int], other: ExprOperand) -> Expr: ...
    def __rrshift__(self: Field[int], other: ExprOperand) -> Expr: ...


AnyField = Field[ScalarValue]
FieldOverride = T | Fixed[T] | Field[T]


class MemberRef(Generic[T_co]):
    """A Field reference bound through a nested Schema instance."""
    @property
    def name(self) -> str: ...
    def __add__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __radd__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __sub__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __rsub__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __mul__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __rmul__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __floordiv__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __rfloordiv__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __mod__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __rmod__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __eq__(self: MemberRef[int] | MemberRef[str], other: ExprOperand) -> Expr: ...  # type: ignore[override]
    def __ne__(self: MemberRef[int] | MemberRef[str], other: ExprOperand) -> Expr: ...  # type: ignore[override]
    def __lt__(self: MemberRef[int] | MemberRef[str], other: ExprOperand) -> Expr: ...
    def __le__(self: MemberRef[int] | MemberRef[str], other: ExprOperand) -> Expr: ...
    def __gt__(self: MemberRef[int] | MemberRef[str], other: ExprOperand) -> Expr: ...
    def __ge__(self: MemberRef[int] | MemberRef[str], other: ExprOperand) -> Expr: ...
    def __and__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __or__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __ror__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __xor__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __rxor__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __lshift__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __rlshift__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __rshift__(self: MemberRef[int], other: ExprOperand) -> Expr: ...
    def __rrshift__(self: MemberRef[int], other: ExprOperand) -> Expr: ...


ExprOperand = int | float | bool | str | Fixed[int] | Fixed[str] | Field[int] | Field[str] | MemberRef[int] | MemberRef[str] | _ConstraintNode | Expr
ConstraintInput = str | Callable[[T], bool]
Length = int | Field[int] | MemberRef[int] | Fixed[int] | Expr
FixedInput = T | Fixed[T]


class Occurs:
    """Inclusive ``minOccurs`` / ``maxOccurs`` bounds."""
    min_occurs: int
    max_occurs: int
    def __init__(self, min_occurs: int, max_occurs: int) -> None: ...


class ScalarType(Generic[T]):
    def __call__(self, value: FixedInput[T] | None = None, *, constraint: ConstraintInput[T] | None = None,
                 field_id: str | None = None, mutable: bool | None = None,
                 token: bool | None = None, value_type: str | None = None) -> Field[T]: ...


class IntegerType(ScalarType[int]):
    def __call__(self, value: FixedInput[int] | None = None, *, endian: Endian | None = None,
                 signed: bool | None = None, constraint: ConstraintInput[int] | None = None,
                 field_id: str | None = None, mutable: bool | None = None,
                 token: bool | None = None, value_type: str | None = None) -> Field[int]: ...


class DoubleType(ScalarType[float]):
    def __call__(self, value: FixedInput[float] | None = None, *, size: Literal[32, 64] = 64,
                 endian: Endian | None = None, constraint: ConstraintInput[float] | None = None,
                 field_id: str | None = None, mutable: bool | None = None,
                 token: bool | None = None, value_type: str | None = None) -> Field[float]: ...


class ExtendedType(Generic[ExtendedValue]):
    """Create a custom scalar factory for a supported scalar value type."""
    def __init__(self, name: str) -> None: ...
    def __call__(self, value: FixedInput[ExtendedValue] | None = None, /,
                 **attributes: int | float | bool | str) -> Field[ExtendedValue]: ...


class BoundSizedType(Generic[T]):
    def __call__(self, value: FixedInput[T] | None = None, *, constraint: ConstraintInput[T] | None = None,
                 field_id: str | None = None,
                 length_type: str | None = None, mutable: bool | None = None,
                 token: bool | None = None, value_type: str | None = None) -> Field[T]: ...


class BoundStringType(BoundSizedType[str]):
    def __call__(self, value: FixedInput[str] | None = None, *, constraint: ConstraintInput[str] | None = None,
                 field_id: str | None = None,
                 length_type: str | None = None, mutable: bool | None = None,
                 token: bool | None = None, value_type: str | None = None,
                 type: StringEncoding | None = None, null_terminated: bool | None = None,
                 pad_character: str | None = None) -> Field[str]: ...


class BoundDecimalStringType(BoundSizedType[int]):
    def __call__(self, value: FixedInput[int] | None = None, *, constraint: ConstraintInput[int] | None = None,
                 field_id: str | None = None,
                 length_type: str | None = None, mutable: bool | None = None,
                 token: bool | None = None, value_type: str | None = None,
                 type: StringEncoding | None = None, null_terminated: bool | None = None,
                 pad_character: str | None = None) -> Field[int]: ...


class SizedType(Generic[T]):
    def __call__(self, value: FixedInput[T] | None = None) -> Field[T]: ...
    def __getitem__(self, length: Length) -> BoundSizedType[T]: ...


class StringType(SizedType[str]):
    def __getitem__(self, length: Length) -> BoundStringType: ...
    def __call__(self, value: FixedInput[str] | None = None, *, constraint: ConstraintInput[str] | None = None,
                 field_id: str | None = None, length_type: str | None = None,
                 mutable: bool | None = None, token: bool | None = None,
                 value_type: str | None = None, type: StringEncoding | None = None,
                 null_terminated: bool | None = None, pad_character: str | None = None) -> Field[str]: ...


class DecimalStringType(ScalarType[int]):
    """Create a base-10 integer encoded as a Peach String."""
    def __getitem__(self, length: Length) -> BoundDecimalStringType: ...
    def __call__(self, value: FixedInput[int] | None = None, *, constraint: ConstraintInput[int] | None = None,
                 field_id: str | None = None, length_type: str | None = None,
                 mutable: bool | None = None, token: bool | None = None,
                 value_type: str | None = None, type: StringEncoding | None = None,
                 null_terminated: bool | None = None, pad_character: str | None = None) -> Field[int]: ...


class _SchemaInstance:
    """Base for Schema references. Keyword arguments override scalar or nested Schema members."""
    def __init__(self, **overrides: Override) -> None: ...
    def __call__(self, **overrides: Override) -> Self: ...
    def clone_unbound(self) -> Self: ...
    def bind_to(self, container: _SchemaInstance, path: tuple[str, ...]) -> Self: ...


class Schema(_SchemaInstance):
    """Base class for a named binary structure."""
    def __or__(self, other: type[Schema] | SchemaUnion) -> SchemaUnion: ...


class SchemaUnion:
    """Unnamed union, normally written ``First | Second``."""
    def __call__(self) -> SchemaUnion: ...
    @overload
    def __get__(self, instance: None, owner: type[Schema]) -> SchemaUnion: ...
    @overload
    def __get__(self, instance: _SchemaInstance, owner: type[Schema]) -> BoundSchemaUnion: ...

class BoundSchemaUnion:
    def __getattr__(self, name: str) -> _SchemaInstance: ...


class NamedUnion:
    """Named alternatives, constructed with ``Union(first=First, second=Second)``."""
    def __call__(self, **overrides: type[Schema] | Schema | Field[int] | Field[float] | Field[str] | Field[bytes] | BlockField[Any]) -> NamedUnion: ...
    @overload
    def __get__(self, instance: None, owner: type[Schema]) -> NamedUnion: ...
    @overload
    def __get__(self, instance: _SchemaInstance, owner: type[Schema]) -> BoundNamedUnion: ...

class BoundNamedUnion:
    def __getattr__(self, name: str) -> Any: ...


class UnionType:
    @overload
    def __call__(self, definition: type[T], /) -> T: ...
    @overload
    def __call__(self, **alternatives: type[Schema] | Schema | Field[int] | Field[float] | Field[str] | Field[bytes] | BlockField[Any]) -> NamedUnion: ...


class ArrayField(Generic[T_co]):
    @overload
    def __get__(self, instance: None, owner: type[Schema]) -> ArrayField[T_co]: ...
    @overload
    def __get__(self, instance: _SchemaInstance, owner: type[Schema]) -> BoundArrayField[T_co]: ...

class BoundArrayField(Generic[T_co]):
    def internal(self) -> T_co: ...

class OptionalField(Generic[T_co]):
    @overload
    def __get__(self, instance: None, owner: type[Schema]) -> OptionalField[T_co]: ...
    @overload
    def __get__(self, instance: _SchemaInstance, owner: type[Schema]) -> BoundOptionalField[T_co]: ...

class BoundOptionalField(Generic[T_co]):
    def internal(self) -> T_co: ...
class BlockField(Generic[T_co]):
    @overload
    def __get__(self, instance: None, owner: type[Schema]) -> BlockField[T_co]: ...
    @overload
    def __get__(self, instance: _SchemaInstance, owner: type[Schema]) -> T_co: ...
    def __call__(self, **overrides: Override) -> T_co: ...

SchemaMember = AnyField | _SchemaInstance | SchemaUnion | NamedUnion | ArrayField[Any] | OptionalField[ScalarValue] | BlockField[Any]
Override = BlockField[Any] | FieldOverride[ScalarValue] | _SchemaInstance
ArrayElementInput = ScalarType[int] | ScalarType[float] | SizedType[int] | SizedType[str] | SizedType[bytes] | BoundSizedType[int] | BoundSizedType[str] | BoundSizedType[bytes] | Field[int] | Field[float] | Field[str] | Field[bytes] | _SchemaInstance | SchemaUnion | NamedUnion | ArrayField[Any] | type[Schema]


class BoundArrayType(Generic[T_co]):
    def __call__(self) -> ArrayField[T_co]: ...
class ArrayType:
    """Declare bounded repetition or ``Array[Element]()`` until parsing stops."""
    @overload
    def __getitem__(self, element: ScalarType[T] | SizedType[T] | BoundSizedType[T] | Field[T]) -> BoundArrayType[MemberRef[T]]: ...
    @overload
    def __getitem__(self, element: type[S]) -> BoundArrayType[S]: ...
    @overload
    def __getitem__(self, element: S) -> BoundArrayType[S]: ...
    @overload
    def __getitem__(self, element: SchemaUnion | NamedUnion | ArrayField[Any]) -> BoundArrayType[Any]: ...
    @overload
    def __getitem__(self, parameters: tuple[ScalarType[T] | SizedType[T] | BoundSizedType[T] | Field[T], Length | Occurs]) -> BoundArrayType[MemberRef[T]]: ...
    @overload
    def __getitem__(self, parameters: tuple[type[S], Length | Occurs]) -> BoundArrayType[S]: ...
    @overload
    def __getitem__(self, parameters: tuple[S, Length | Occurs]) -> BoundArrayType[S]: ...
    @overload
    def __getitem__(self, parameters: tuple[SchemaUnion | NamedUnion | ArrayField[Any], Length | Occurs]) -> BoundArrayType[Any]: ...


class BoundOptionalType(Generic[T_co]):
    def __call__(self, constraint: FixedInput[ScalarValue] | None = None, *, when: Expr | None = None) -> OptionalField[T_co]: ...
class OptionalType:
    """Declare an optional field: ``Optional[Int16](when=count == 2)``."""
    @overload
    def __getitem__(self, element: ScalarType[T] | SizedType[T] | BoundSizedType[T] | Field[T]) -> BoundOptionalType[MemberRef[T]]: ...
    @overload
    def __getitem__(self, element: type[int]) -> BoundOptionalType[MemberRef[int]]: ...
    @overload
    def __getitem__(self, element: type[float]) -> BoundOptionalType[MemberRef[float]]: ...
    @overload
    def __getitem__(self, element: type[str]) -> BoundOptionalType[MemberRef[str]]: ...
    @overload
    def __getitem__(self, element: type[bytes]) -> BoundOptionalType[MemberRef[bytes]]: ...
    @overload
    def __getitem__(self, element: type[S]) -> BoundOptionalType[S]: ...
    @overload
    def __getitem__(self, element: S) -> BoundOptionalType[S]: ...
    @overload
    def __getitem__(self, element: SchemaUnion | NamedUnion | ArrayField[Any]) -> BoundOptionalType[Any]: ...


class BoundBlockType:
    @overload
    def __call__(self, schema: type[S], /) -> BlockField[S]: ...
    @overload
    def __call__(self, **fields: Field[int] | Field[float] | Field[str] | Field[bytes] | _SchemaInstance | SchemaUnion | NamedUnion | ArrayField[Any] | OptionalField[Any] | BlockField[Any] | type[Schema] | Override) -> BlockField[Any]: ...
class BlockType:
    """Declare a direct or decorated Block, optionally with ``Block[length]``."""
    @overload
    def __call__(self, schema: type[S], /) -> BlockField[S]: ...
    @overload
    def __call__(self, **fields: Field[int] | Field[float] | Field[str] | Field[bytes] | _SchemaInstance | SchemaUnion | NamedUnion | ArrayField[Any] | OptionalField[Any] | BlockField[Any] | type[Schema] | Override) -> BlockField[Any]: ...
    def __getitem__(self, length: Length) -> BoundBlockType: ...


class Flags:
    """Decorate a Schema whose ``Bit`` members occupy a packed integer."""
    def __init__(self, storage: IntegerType, *, endian: Endian) -> None: ...
    def __call__(self, schema: type[S]) -> type[S]: ...


class Default:
    """Decorate a Schema with inherited number defaults for ``endian`` and ``signed``."""
    def __init__(self, *, endian: Endian | None = None, signed: bool | None = None) -> None: ...
    def __call__(self, schema: type[S]) -> type[S]: ...


def PacketUnion(schema: type[S]) -> type[S]: ...


class FieldReference:
    name: str
    value_cast: str | None
    def __init__(self, name: str, value_cast: str | None = None) -> None: ...
class ExprResult:
    operation: str
class FieldResult:
    name: str
    kind: str
    fixed: Fixed[ScalarValue] | None
    value: ScalarValue | None
    path: str | None
class SchemaResult:
    name: str
    fields: Mapping[str, FieldResult | SchemaResult | UnionResult | ArrayResult | OptionalResult]
    packet_union: str | None
    path: str | None
class UnionResult:
    alternatives: tuple[FieldResult | SchemaResult, ...]
    path: str | None
class ArrayResult:
    name: str
    element: FieldResult | SchemaResult | UnionResult | ArrayResult
    count: int | FieldReference | ExprResult | Occurs | None
    path: str | None
class OptionalResult:
    name: str
    element: FieldResult | SchemaResult | UnionResult | ArrayResult
    condition: ExprResult
    path: str | None
    source_path: str | None

SchemaInput = type[Schema] | Schema | SchemaUnion | NamedUnion
EvaluationResult = SchemaResult | UnionResult
ResultMember = FieldResult | SchemaResult | UnionResult | ArrayResult | OptionalResult
def evaluate_schema(target: SchemaInput) -> EvaluationResult:
    """Evaluate a DSL declaration into an immutable, inspectable result tree."""
def format_schema_result(result: EvaluationResult) -> str: ...
def to_peach_data_model(target: SchemaInput, *, name: str | None = None, include_header: bool = True) -> str:
    """Export Peach XML; PacketUnion schemas become dependency-ordered DataModels."""


Double: DoubleType
String: StringType
DecimalString: DecimalStringType
Int4: IntegerType
Int8: IntegerType
Int16: IntegerType
Int32: IntegerType
Int64: IntegerType
Bit: SizedType[int]
Blob: SizedType[bytes]
Array: ArrayType
Optional: OptionalType
Block: BlockType
Union: UnionType
